### ISSUE TITLE
Cannot load two books by URL in same session

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#61]
This error appears on second book:

```
TypeError: Cannot read properties of undefined (reading 'outerHTML')
    at t.embedPreviewTextInGrafts (_app-7d92365e7b11cd77.js:204:202584)
    at _app-7d92365e7b11cd77.js:204:188935
    at Object.useMemo (framework-0ba0ddd33199226d.js:1:69563)
    at n.useMemo (framework-0ba0ddd33199226d.js:1:136651)
```

**Comment by mandolyte** [comment]
This seems to be fixed in v0.0.13. Not sure why!

**Comment by larsgson** [comment]
Yes, after looking at the PR #66 it definitely looks like this is solved. Do you agree that we can close this issue now?

**Comment by mandolyte** [comment]
Agree
